name: Start Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      # Check the project api [ lampda method ]
        # Create lampda method
          # check if the instnace is up and running

      # Check the project endpoint
      - name: Start Deployment
        run: echo "Initalize Deployment"
      
      - name: Delpoy Application Into
        run: echo "Start deploying the server"